# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20171018_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='photolist',
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.TextField(default='', verbose_name='播放列表'),
        ),
        migrations.AlterField(
            model_name='video',
            name='count',
            field=models.IntegerField(default=0, verbose_name='视频数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(upload_to='cover/', verbose_name='视频封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.CharField(max_length=64, verbose_name='视频标示'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=64, verbose_name='视频标题'),
        ),
    ]
